# Generated by Django 5.1.4 on 2025-04-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAFE_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
