# Generated by Django 5.1.4 on 2025-08-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAFE_APP', '0006_alter_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
